apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 2  # Run 2 instances of the application
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: yourdockerhubusername/sample-app:latest  # Replace with your Docker Hub username
        ports:
        - containerPort: 5000
