apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  selector:
    app: sample-app
  type: LoadBalancer  # Expose service externally
  ports:
  - protocol: TCP
    port: 80          # Expose service on port 80
    targetPort: 5000  # Redirect traffic to container port 5000
